In [3]:
import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file into a DataFrame
df = pd.read_csv('UNWTO_tourism_data.csv')

# Melt the DataFrame to reshape it
melted_df = pd.melt(df, id_vars=['Country', 'Report Type', 'Category', 'Subcategory', 'Metric'], var_name='Year', value_name='Value')

In [4]:
df

,Country,Report Type,Category,Subcategory,Metric,1995,1996,1997,1998,1999,...,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022
0,AFGHANISTAN,Domestic Tourism-Accommodation,Accommodation,Hotels and similar establishments,Guests,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFGHANISTAN,Domestic Tourism-Accommodation,Accommodation,Hotels and similar establishments,Overnights,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFGHANISTAN,Domestic Tourism-Accommodation,Accommodation,Total,Guests,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFGHANISTAN,Domestic Tourism-Accommodation,Accommodation,Total,Overnights,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFGHANISTAN,Domestic Tourism-Trips,Trips,Total trips,Overnights visitors (tourists),NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8248,ZIMBABWE,Tourism Industries,Accommodation for visitors in hotels and simil...,Number of bed-places,Number of bed-places,8659.0,8661.0,9241.0,9462.0,8646.0,...,13195.0,13195.0,12772.0,12772.0,12772.0,12772.0,13158.0,14551.0,14551.0,14469.0
8249,ZIMBABWE,Tourism Industries,Accommodation for visitors in hotels and simil...,Number of establishments,Number of establishments,NaN,NaN,NaN,NaN,NaN,...,99.0,99.0,96.0,96.0,96.0,96.0,97.0,95.0,95.0,75.0
8250,ZIMBABWE,Tourism Industries,Accommodation for visitors in hotels and simil...,Number of rooms,Number of rooms,4378.0,4422.0,4545.0,4932.0,5069.0,...,6722.0,6722.0,6483.0,6483.0,6483.0,6483.0,6676.0,7217.0,7217.0,7177.0
8251,ZIMBABWE,Tourism Industries,Accommodation for visitors in hotels and simil...,Occupancy rate / bed-places,Occupancy rate / bed-places,49.1,50.3,52.0,49.0,42.0,...,37.0,36.0,31.0,33.0,35.0,39.0,32.0,15.0,18.0,30.0
8252,ZIMBABWE,Tourism Industries,Accommodation for visitors in hotels and simil...,Occupancy rate / rooms,Occupancy rate / rooms,NaN,NaN,NaN,NaN,NaN,...,48.0,48.0,47.0,46.0,48.0,53.0,44.0,19.0,27.0,44.0

In [6]:
df = df.T

In [7]:
df

,0,1,2,3,4,5,6,7,8,9,...,8243,8244,8245,8246,8247,8248,8249,8250,8251,8252
Country,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,AFGHANISTAN,...,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE,ZIMBABWE
Report Type,Domestic Tourism-Accommodation,Domestic Tourism-Accommodation,Domestic Tourism-Accommodation,Domestic Tourism-Accommodation,Domestic Tourism-Trips,Domestic Tourism-Trips,Domestic Tourism-Trips,Employment,Employment,Employment,...,Outbound Tourism-Departures,Outbound Tourism-Expenditure,Outbound Tourism-Expenditure,Outbound Tourism-Expenditure,Tourism Industries,Tourism Industries,Tourism Industries,Tourism Industries,Tourism Industries,Tourism Industries
Category,Accommodation,Accommodation,Accommodation,Accommodation,Trips,Trips,Trips,Number of employees by tourism industries,Number of employees by tourism industries,Number of employees by tourism industries,...,Departures,Tourism expenditure in other countries,Tourism expenditure in other countries,Tourism expenditure in other countries,Accommodation for visitors in hotels and simil...,Accommodation for visitors in hotels and simil...,Accommodation for visitors in hotels and simil...,Accommodation for visitors in hotels and simil...,Accommodation for visitors in hotels and simil...,Accommodation for visitors in hotels and simil...
Subcategory,Hotels and similar establishments,Hotels and similar establishments,Total,Total,Total trips,Total trips,Total trips,Total,Total,Total,...,Total departures,Passenger transport,Passenger transport,Travel,Average length of stay,Number of bed-places,Number of establishments,Number of rooms,Occupancy rate / bed-places,Occupancy rate / rooms
Metric,Guests,Overnights,Guests,Overnights,Overnights visitors (tourists),Same-day visitors (excursionists),Total,Accommodation services for visitors (hotels an...,Food and beverage serving activities,Other accommodation services,...,Total,Passenger transport,Total,Travel,Average length of stay,Number of bed-places,Number of establishments,Number of rooms,Occupancy rate / bed-places,Occupancy rate / rooms
1995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,106.0,NaN,NaN,8659.0,NaN,4378.0,49.1,NaN
1996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,118.0,NaN,NaN,8661.0,NaN,4422.0,50.3,NaN
1997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,120.0,NaN,NaN,9241.0,NaN,4545.0,52.0,NaN
1998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,131.0,NaN,NaN,9462.0,NaN,4932.0,49.0,NaN
1999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,8646.0,NaN,5069.0,42.0,NaN
2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,9427.0,NaN,5206.0,29.0,NaN
2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,11723.0,NaN,5590.0,31.0,NaN
2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,12053.0,NaN,5766.0,36.0,NaN
2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,12053.0,NaN,5766.0,46.0,NaN
2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,12053.0,NaN,5766.0,43.0,NaN
2005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,11282.0,NaN,5657.0,28.0,39.0
2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,11578.0,NaN,6022.0,27.0,38.0
2007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,11609.0,NaN,6266.0,32.0,43.0
2008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,11855.0,NaN,6319.0,33.0,41.0
2009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,57.0,167.0,110.0,3.0,12190.0,120.0,6360.0,35.0,46.0
2010,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,72.0,203.0,131.0,3.0,11981.0,121.0,6248.0,36.0,52.0
2011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,89.0,317.0,228.0,3.0,11935.0,116.0,6360.0,37.0,52.0
2012,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,115.0,387.0,272.0,3.0,12081.0,116.0,6427.0,37.0,52.0
2013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,104.0,441.0,337.0,3.0,13195.0,99.0,6722.0,37.0,48.0
2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,109.0,451.0,342.0,3.0,13195.0,99.0,6722.0,36.0,48.0
2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,81.0,557.0,476.0,3.0,12772.0,96.0,6483.0,31.0,47.0
2016,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79.0,406.0,327.0,3.0,12772.0,96.0,6483.0,33.0,46.0
2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,22.0,337.0,315.0,3.0,12772.0,96.0,6483.0,35.0,48.0
2018,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,21.0,269.0,248.0,3.0,12772.0,96.0,6483.0,39.0,53.0
2019,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,53.0,257.0,204.0,3.0,13158.0,97.0,6676.0,32.0,44.0
2020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,22.0,157.0,135.0,3.0,14551.0,95.0,7217.0,15.0,19.0
2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,14551.0,95.0,7217.0,18.0,27.0
2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,14469.0,75.0,7177.0,30.0,44.0

In [8]:
print(df.head())
print(df.info())
print(df.describe(include='all'))

                                          0     \
Country                            AFGHANISTAN
Report Type     Domestic Tourism-Accommodation
Category                         Accommodation
Subcategory  Hotels and similar establishments
Metric                                  Guests

                                          1     \
Country                            AFGHANISTAN
Report Type     Domestic Tourism-Accommodation
Category                         Accommodation
Subcategory  Hotels and similar establishments
Metric                              Overnights

                                       2                               3     \
Country                         AFGHANISTAN                     AFGHANISTAN
Report Type  Domestic Tourism-Accommodation  Domestic Tourism-Accommodation
Category                      Accommodation                   Accommodation
Subcategory                           Total                           Total
Metric                               Guests                      Overnights

                                       4     \
Country                         AFGHANISTAN
Report Type          Domestic Tourism-Trips
Category                              Trips
Subcategory                     Total trips
Metric       Overnights visitors (tourists)

                                          5                       6     \
Country                            AFGHANISTAN             AFGHANISTAN
Report Type             Domestic Tourism-Trips  Domestic Tourism-Trips
Category                                 Trips                   Trips
Subcategory                        Total trips             Total trips
Metric       Same-day visitors (excursionists)                   Total

                                                          7     \
Country                                            AFGHANISTAN
Report Type                                         Employment
Category             Number of employees by tourism industries
Subcategory                                              Total
Metric       Accommodation services for visitors (hotels an...

                                                  8     \
Country                                    AFGHANISTAN
Report Type                                 Employment
Category     Number of employees by tourism industries
Subcategory                                      Total
Metric            Food and beverage serving activities

                                                  9     ...  \
Country                                    AFGHANISTAN  ...
Report Type                                 Employment  ...
Category     Number of employees by tourism industries  ...
Subcategory                                      Total  ...
Metric                    Other accommodation services  ...

                                    8243  \
Country                         ZIMBABWE
Report Type  Outbound Tourism-Departures
Category                      Departures
Subcategory             Total departures
Metric                             Total

                                               8244  \
Country                                    ZIMBABWE
Report Type            Outbound Tourism-Expenditure
Category     Tourism expenditure in other countries
Subcategory                     Passenger transport
Metric                          Passenger transport

                                               8245  \
Country                                    ZIMBABWE
Report Type            Outbound Tourism-Expenditure
Category     Tourism expenditure in other countries
Subcategory                     Passenger transport
Metric                                        Total

                                               8246  \
Country                                    ZIMBABWE
Report Type            Outbound Tourism-Expenditure
Category     Tourism expenditure in other countries
Subcategory                                  Travel
Metric                                       Travel

                                                          8247  \
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                             Average length of stay
Metric                                  Average length of stay

                                                          8248  \
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                               Number of bed-places
Metric                                    Number of bed-places

                                                          8249  \
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                           Number of establishments
Metric                                Number of establishments

                                                          8250  \
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                                    Number of rooms
Metric                                         Number of rooms

                                                          8251  \
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                        Occupancy rate / bed-places
Metric                             Occupancy rate / bed-places

                                                          8252
Country                                               ZIMBABWE
Report Type                                 Tourism Industries
Category     Accommodation for visitors in hotels and simil...
Subcategory                             Occupancy rate / rooms
Metric                                  Occupancy rate / rooms

[5 rows x 8253 columns]
<class 'pandas.core.frame.DataFrame'>
Index: 33 entries, Country to 2022
Columns: 8253 entries, 0 to 8252
dtypes: object(8253)
memory usage: 2.1+ MB
None
               0            1            2            3            4     \
count             5            5            5            5            5
unique            5            5            5            5            5
top     AFGHANISTAN  AFGHANISTAN  AFGHANISTAN  AFGHANISTAN  AFGHANISTAN
freq              1            1            1            1            1

               5            6            7            8            9     ...  \
count             5            5            5            5            5  ...
unique            5            5            5            5            5  ...
top     AFGHANISTAN  AFGHANISTAN  AFGHANISTAN  AFGHANISTAN  AFGHANISTAN  ...
freq              1            1            1            1            1  ...

            8243                 8244      8245    8246  8247     8248  8249  \
count          5                   17        21      17  26.0     33.0  19.0
unique         5                   15        21      16   7.0     25.0  12.0
top     ZIMBABWE  Passenger transport  ZIMBABWE  Travel   3.0  12772.0  96.0
freq           1                    2         1       2  19.0      4.0   4.0

          8250  8251  8252
count     33.0  33.0  23.0
unique    24.0  24.0  17.0
top     6483.0  37.0  52.0
freq       4.0   3.0   3.0

[4 rows x 8253 columns]

In [12]:
df_melted = df.melt(id_vars=['Afganistan'], var_name='Country', value_name='Value')
print("\nMelted DataFrame:")
print(df_melted.head())

KeyError: "The following id_vars or value_vars are not present in the DataFrame: ['Afganistan']"